import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export default function About() {
  return (
    <div className="min-h-screen">
      <div className="relative isolate overflow-hidden bg-white lg:overflow-visible lg:px-0 ">
        <Navbar
          isLanding={false}
          isAbout={true}
          isResource={false}
          isLogIn={false}
        />
        <div className="absolute inset-0 -z-10 overflow-hidden">
          <svg
            className="absolute left-[max(50%,25rem)] top-0 h-[64rem] w-[128rem] -translate-x-1/2 stroke-gray-200 [mask-image:radial-gradient(64rem_64rem_at_top,white,transparent)]"
            aria-hidden="true"
          >
            <defs>
              <pattern
                id="e813992c-7d03-4cc4-a2bd-151760b470a0"
                width={200}
                height={200}
                x="50%"
                y={-1}
                patternUnits="userSpaceOnUse"
              >
                <path d="M100 200V.5M.5 .5H200" fill="none" />
              </pattern>
            </defs>
            <svg x="50%" y={-1} className="overflow-visible fill-gray-50">
              <path
                d="M-100.5 0h201v201h-201Z M699.5 0h201v201h-201Z M499.5 400h201v201h-201Z M-300.5 600h201v201h-201Z"
                strokeWidth={0}
              />
            </svg>
            <rect
              width="100%"
              height="100%"
              strokeWidth={0}
              fill="url(#e813992c-7d03-4cc4-a2bd-151760b470a0)"
            />
          </svg>
        </div>
        <div className="mx-10 sm:mx-16 py-12 lg:py-16 lg:mx-0  lg:items-start lg:gap-y-10">
          <div className="pb-16 lg:col-span-2 lg:col-start-1 lg:row-start-1 lg:mx-auto  lg:w-full lg:max-w-7xl  lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className=" ">
                <p className="text-base font-semibold leading-7 text-blue-600 ps-2 dark:text-blue-500">
                  About Wisdomous
                </p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                  Prompting Playground
                </h1>
                <p className="mt-6 text-xl leading-8 text-gray-700">
                  The widespread integration of generative AI, particularly
                  Large Language Models (LLMs), has profoundly influenced
                  various domains. However, a persistent challenge lies in the
                  variability of responses generated by these AI systems.
                  Inconsistent responses pose the risk of misinformation and a
                  decline in trust in AI systems. Prompt engineering emerges as
                  a critical factor in optimizing human-AI interactions, where
                  the quality of prompts significantly influences the responses
                  of generative AI systems. Wisdomous addresses the need for
                  more effective prompts by empowering users to input their
                  prompts and collaboratively refine them using AI-driven
                  capabilities. Wisdomous emerged not just as a platform but as
                  a reflection of the transformative potential of human
                  creativity and AI innovation.
                </p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-2 lg:max-w-7xl lg:col-start-1 lg:row-start-2 lg:mx-auto lg:w-full lg:gap-x-8 lg:px-8">
            <div className="lg:pr-4">
              <div className=" text-base leading-7 text-gray-700 ">
                <p>
                  At Wisdomous, we're committed to equipping you with the tools
                  and resources necessary to optimize your prompts effectively.
                  Our platform is designed with simplicity and efficiency in
                  mind, empowering you to craft prompts that drive impactful AI
                  interactions. This where prompt engineering excels. Gone are
                  the days of manual prompt tweaking and guesswork. With
                  Wisdomous, prompt engineering is as seamless as it is
                  effective. Our platform guides you through the optimization
                  process step by step, ensuring that every prompt you create is
                  optimized for maximum impact.
                </p>

                <div className="relative overflow-hidden mt-16 rounded-xl px-4">
                  <div className="px-4 py-12 sm:px-6 lg:px-8 lg:py-16 mx-auto">
                    <div
                      aria-hidden="true"
                      className="flex absolute start-0 -z-[1]"
                    >
                      <div className="bg-purple-400 opacity-20 blur-3xl w-[1036px] h-[300px] dark:bg-purple-900 dark:opacity-20"></div>
                    </div>
                    <div className="lg:items-center">
                      <blockquote>
                        <h3 className="text-2xl pb-3 font-semibold text-blue-600 dark:text-blue-500">
                          The name "Wisdomous"
                        </h3>
                        <p className="text-xl text-gray-600 lg:text-2xl lg:leading-normal dark:text-gray-200">
                          Implies a tool that goes beyond simple prompt
                          generation, emphasizing a thoughtful and wise
                          approach. It suggests that the prompts generated by
                          the tool are formulated with a degree of intelligence.
                          The name communicates a sense of reliability and
                          quality, appealing to users who seek more than just
                          random or generic prompts.
                        </p>
                      </blockquote>
                    </div>
                  </div>
                </div>

                <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">
                  Experience Wisdomous Today
                </h2>
                <p className="mt-6">
                  Ready to revolutionize your prompt engineering process? Join
                  Wisdomous today and experience the difference for yourself.
                  With our user-friendly platform and powerful optimization
                  tools, you'll be well-equipped to create prompts that drive
                  meaningful AI interactions. Get started now and unlock the
                  full potential of your prompts with Wisdomous.
                </p>
                <div className="mt-8 gap-3 flex justify-center">
                  <a
                    className="inline-flex px-12 justify-center items-center gap-x-3 text-center bg-gradient-to-tl from-blue-600 to-violet-600 hover:from-violet-600 hover:to-blue-600 border border-transparent text-white text-sm font-medium rounded-full focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white py-3 dark:focus:ring-offset-gray-800"
                    href="/login"
                  >
                     Sign Up
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
